version: "3"
services:
  selenium:
    image: selenium/standalone-chrome-debug:3.2.0-actinium
    shm_size: "2gb"
    ports:
      - 4444:4444
      - 5900:5900
  app:
    build: ./app
    volumes:
      - ./app:/app
    environment:
      SELENIUM_URL: http://selenium:4444/wd/hub
    tty: true
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    ports:
      - '3308:3306'
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $password
      MYSQL_DATABASE: $MYSQL_DATABASE